// <auto-generated />
using EasyBlog.DataAccess.CompiledModels;
using EasyBlog.DataAccess.SqlLite;
using Microsoft.EntityFrameworkCore.Infrastructure;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(EasyBlogDbContextSqLite), typeof(EasyBlogDbContextSqLiteModel))]
