// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace EasyBlog.DataAccess.CompiledModels
{
    public partial class EasyBlogDbContextSqLiteModel
    {
        private EasyBlogDbContextSqLiteModel()
            : base(skipDetectChanges: false, modelId: new Guid("b9d63f99-2107-485b-ab88-f4991db58c24"), entityTypeCount: 3)
        {
        }

        partial void Initialize()
        {
            var postEntity = PostEntityEntityType.Create(this);
            var tagEntity = TagEntityEntityType.Create(this);
            var postsTags = PostsTagsEntityType.Create(this);

            PostsTagsEntityType.CreateForeignKey1(postsTags, postEntity);
            PostsTagsEntityType.CreateForeignKey2(postsTags, tagEntity);

            PostEntityEntityType.CreateSkipNavigation1(postEntity, tagEntity, postsTags);
            TagEntityEntityType.CreateSkipNavigation1(tagEntity, postEntity, postsTags);

            PostEntityEntityType.CreateAnnotations(postEntity);
            TagEntityEntityType.CreateAnnotations(tagEntity);
            PostsTagsEntityType.CreateAnnotations(postsTags);

            AddAnnotation("ProductVersion", "10.0.0-preview.3.25171.6");
        }
    }
}
