namespace EasyBlog.DataAccess.Relational.Entities;

[Table("Languages")] //TODO Think about no sql, maybe fluent will be better, but for now it's ok
[Index(nameof(Code), IsUnique = true)]
[Index(nameof(Name), IsUnique = true)]
public class LanguageEntity
{
    [Key] //TODO Autogenerated or predefined dictionary
    public int Id { get; set; }

    [Required, MaxLength(DbDefaults.Language.NameMaxLength)]
    public string Name { get; set; } = string.Empty;

    [Required, MaxLength(DbDefaults.Language.CodeMaxLength)]
    public string Code { get; set; } = string.Empty;

    public List<PostContentEntity> PostContents { get; set; } = [];
}